trigger:
- main
pool:
  name: 'agent ka jund'

steps: 
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'samaridhi'
    backendAzureRmOverrideSubscriptionID: 'e5476362-58a0-48f7-8197-5aa05a4abfa5'
    backendAzureRmResourceGroupName: 'rajiv'
    backendAzureRmStorageAccountName: 'stg420'
    backendAzureRmContainerName: 'amarendra'
    backendAzureRmKey: 'pipeline_sure_se/terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'samaridhi'
    environmentAzureRmOverrideSubscriptionID: 'e5476362-58a0-48f7-8197-5aa05a4abfa5'
    environmentAzureRmUseIdTokenGeneration: true
